project:
  type: website
  output-dir: docs
  resources: /CNAME


website:
  site-url: https://rayonvina.rbind.io
  favicon: assets/images/icon_FRV_white.png
  title: "Fernando Rayón Viña"
  description: "My personal webpage"
  page-navigation: true
  back-to-top-navigation: true
  twitter-card: true
  google-analytics: 
    tracking-id: "G-F1EM001LSQ"
    storage: none
    anonymize-ip: true
    version: 4
  navbar:
    logo: assets/images/icon_FRV_white.png
    background: primary
    pinned: true
    search: true
    tools:
      - icon: github
        href: https://github.com/RayonVina
    right:
      - text: "About"
        menu:
          - text: "About me"
            href: about/index.qmd
          - text: "Curriculum vitæ"
            href: about/resume.qmd
          - text: "Publications"
            href: about/publications.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Blog"
        href: blog/index.qmd
  
  page-footer:  
    left: >-
      &#169; 2025 Fernando Rayón Viña &#8729; Made with [Quarto](https://quarto.org)
    center:
      <a class="link-dark me-1" href="https://github.com/RayonVina" title="Github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://vgohab.com/" title="Group Webpage" target="_blank" rel="noopener">{{< fa globe >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0000-0002-1622-2180" title="Orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.com/citations?user=CTlje38AAAAJ&hl=es" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>
      <a class="link-dark me-1" href="https://x.com/RayonVina" title="Twitter" target="_blank" rel="noopener">{{< fa brands square-twitter >}}</a>
      <a class="link-dark me-1" href="https://www.researchgate.net/profile/Fernando-Rayon-Vina" title="ResearchGate" target="_blank" rel="noopener">{{< ai researchgate >}}</a>
    right: 
      - text: "Contact"
        aria-label: "Contact Form"
        href: "contact.qmd"
      - text: "License"
        aria-label: "License Details"
        href: license.qmd

format:
  html:
    theme: assets/frv-theme.scss
    toc: true
    code-link: true
    pagetitle: "{{< meta title >}} | Fernando Rayón Viña"
