---
title: "Curriculum Vitae"
format: 
  html: 
    page-layout: full
    toc: true
    toc-depth: 2
    toc-title: "Contents"
header-includes: |
  <link rel="stylesheet" href="../assets/about.css">
resources:
  - ../assets/about.css
---

_Last updated on May 29, 2024_

## Work Experience

- **Senior Applied Scientist** for Zalando (From August 2023)
- **Technical Writer** for Towards Data Science (From April 2022)
- **Data Science Intern** for Google (August 2022 - December 2022)
- **External Consultant** for Amazon (2021 - 2022)
- **Intern** at EU Commission, Brussels (BE), DG-COMP, Chief Economist Office (European Commission, Spring 2016)

## Education

- **Ph.D. Economics**, University of Zurich, 2023
- **Visiting Assistant in Research**, Yale University, Fall Winter 2021-2022
- **M.S. Economics and Social Sciences**, Bocconi University, 2016
- **B.S. Economics and Social Sciences**, Bocconi University, 2014

**Primary interests**: Industrial Organization, Econometrics, Causal Inference   
**Secondary interests**: Competition Policy, Machine Learning, Market Design, Behavioral Economics

## Working Papers

- **Foreclosure Complementarities: Exclusionary Bundling and Predatory Pricing** (with G. Crawford)
- **Algorithmic Collusion Detection**
- **Algorithmic Collusion in Online Marketplaces**
- **Approximation Methods for Large Dynamic Stochastic Games**

## Teaching

- **Instructor** Empirical Industrial Organization (PhD), University of Zurich, Fall 2021
- **T.A.** Machine Learning for Economic Analysis (MSc), University of Zurich, Fall 2020-21
- **Instructor** Programming Practices for Research Economists (PhD), University of Zurich, Winter 2019
- **T.A.** Econometrics for Research Students (PhD), University of Zurich, Fall 2018-19
- **T.A.** Markets, Organizations and Incentives (BSc), Bocconi University, Fall 2016
- **T.A.** Industrial Organization (BSc), Bocconi University, Spring 2017

## Presentations

### 2021
- Asia and Pacific IO Conference (14/12)
- European Winter Meeting of the Econometric Society (13/12)
- Industrial Organization Prospectus Workshop at Yale University (14/10)
- 2nd AI and Policy Conference (14/09)
- Swiss IO Day (10/06)
- Annual Congress of the Swiss Society of Economics and Statistics Microeconomics (14/05)

### 2020/19
- Applied Microeconomics Seminar at University of Zürich (x4)
- Theory Seminar at University of Zürich (x3)

## Academic Activities

- Referee for the Journal of Competition Law and Economics
- Research Assistant for Paolo Pinotti, Eliana La Ferrara, Anna Gibert (Bocconi University, 2016-17)

## Honors, Awards, and Fellowships

- Doc.Mobility Scholarship (09/2021), Swiss National Science Foundation
- 1st place, Machine Learning Datathlon (05/2021), ETH Zurich, Analytics Club
- Doctoral Scholarship (08/2017), University of Zurich

## Thesis Supervisions

- Jannick Sicher (MSc), “Adversarial Approach to Algorithmic Collusion Detection”
- Tim Herter (MSc), “The Effect of U.S. Food Aid on Underweight”
- Andrin Pluss (BSc), “Merger Simulation and Competition Models”
- Yuming Pan (MSc), “The Impact of Free Legal Aid on Criminal Activities”

## Skills

### Computational
- **Computing**: Python, Julia, R, MATLAB, Stata
- **Design**: LaTeX, Markdown, Tableau, CSS
- **Cloud**: AWS, Redshift
- **Other**: Git, SQL, Unix, Docker

### Languages
- **Italian**: native
- **English**: fluent
- **French**: conversational
- **German**: beginner
- **Spanish**: beginner

## References

- Gregory Crawford, University of Zurich
- Armin Schmutzler, University of Zurich
- Damian Kozbur, University of Zurich
- Chiara Fumagalli, Bocconi University

## Contact

- [Website](https://matteocourthoud.github.io)
- [LinkedIn](https://www.linkedin.com/in/matteocourthoud)
- [Twitter](https://twitter.com/matteocourthoud)
- [GitHub](https://github.com/matteocourthoud)
