---
title: "Temperature-dependent growth and sexuality of the ciguatoxin producer dinoflagellate Gambierdiscus spp. in cultures established from the Canary Islands"
author:
  - name: Isabel Ramilo
  - name: Fernando Rayón Viña
    orcid: 0000-0002-1622-2180    
  - name: Rosa Isabel Figueroa
    orcid: 0000-0001-9944-7993
  - name: Ángeles Cuadrado
    orcid: 0000-0003-0089-5249
  - name: Isabel Bravo
    orcid: 0000-0003-3764-745X

date: "2021-12"
slug: temperature-dependent-growth
categories:
  - Publication
  - Gambierdiscus
  - Ciguatera poisoning
  - Benthic dinoflagellates
  - Harmful algae
  - Sexuality
  - Climate change
description: "Harmful Algae"
# publication_short: ""
subtitle: "The study indicates that Gambierdiscus species growth varies with temperature, with G. australes showing the broadest temperature tolerance, suggesting temperature influences their distribution and sexual reproduction may be a response to temperature extremes."
abstract: ""

format: 
  html: 
    page-layout: full
    toc: false
---
<a href="https://doi.org/10.1016/j.hal.2021.102130"><i class="fa-regular fa-newspaper"></i> Find the paper here</a>


## Abstract

Benthic dinoflagellates of the genus Gambierdiscus produce ciguatoxins, compounds that when metabolized in fish and consumed by humans cause ciguatera poisoning (CP). This syndrome, which is widespread in tropical and subtropical regions, has recently been reported also in subtropical-temperate latitudes such as the Canary Islands where CP events have been regularly detected since 2004. This study examined the effect of temperature on the growth of Gambierdiscus isolated from Canary waters: G. australes, G. caribaeus, G. carolinianus, G. excentricus, and G. silvae. From the temperature vs. growth curves, the maximum growth (µm), optimum temperature range for growth (Topt), and the temperature yielding maximum growth (Tm) were estimated for each species. The results revealed temperature-dependent differences in the growth parameters. G. caribaeus had the highest Tm and Topt, followed by G. australes, G. carolinianus, G. silvae, and G excentricus. G. australes tolerated the widest range of temperatures (from 15 °C to 29 °C), which may explain its broader geographic distribution, both worldwide and across the Canary archipelago. Neither G. excentricus nor G. silvae survived at 29 °C whereas G. caribaeus reached mean growth rates (± standard deviation) up to 0.19 ± 0.01 div.day−1 at that temperature, followed by G. australes (0.16 ± 0.01 div.day−1) and G. carolinianus (0.14 ± 0.04 div.day−1). G. caribaeus showed no measurable growth at 19°C, whereas G. excentricus and G. silvae along with G. australes appeared as the species better adapted to lower temperatures. In an intraspecific variability study of 12 strains of G. australes, the mean (± standard deviation) of µm and Tm were 0.17 ± 0.01 div.day−1 and 27.7 ± 0.5 °C, respectively. An analysis of the shapes and position of the cell nuclei at the different temperatures showed that nuclei characteristic of vegetative cells appeared mainly at 26 °C but extreme temperatures resulted in nuclei with a more variable morphology. The presence of putative zygotes at extreme temperatures (17 °C, 19 °C and 29 °C) suggests that sexual reproduction is promoted as an adaptive strategy which could play an important role in the expansion of geographic distribution of Gambierdiscus species.

<a href="../publications.html"><i class="fas fa-arrow-left"></i> Back to Publications</a>