---
title: "Public awareness of beach litter and alien invasions: Implications for early detection and management"
author:
  - name: Fernando Rayón Viña
    orcid: 0000-0002-1622-2180    
  - name: Sara Fernández Rodríguez
  - name: Aitor Ibabe Arrieta
    orcid: 0000-0003-4146-1842
  - name: Eduardo Dopico
    orcid: 0000-0001-6777-5407
  - name: Eva García Vázquez
    orcid: 0000-0002-8429-838X

date: "2022-03"
slug: public-awareness
categories:
  - Publication
  - Coastal degradation
  - Invasive alien species
  - Litter deposition
  - Social perception
  - Awareness
description: "Ocean & Coastal Management"
publication_short: "OCM"
subtitle: "The research indicates that improving environmental awareness, especially among students, is crucial to address the interconnected issues of littering, invasive species, and coastal degradation in the Bay of Biscay."
abstract: ""
links:
  - icon: file-richtext-fill
    name: Publication
    url: https://doi.org/10.1016/j.ocecoaman.2022.106040
    
format: 
  html: 
    page-layout: full
    toc: false
---

## Abstract

Coastal areas are environments of high diversity and severely threatened by hazards as marine litter and biological invasions. Citizens’ knowledge and awareness are drivers of changes needed to improve environment conservation. Density both of litter and IAS Cortaderia selloana were measured from six beaches in southwest Bay of Biscay along with awareness of inhabitants of the zone using a social survey. Relationship between beach littering, alien invasion and perception and awareness of adults and students were assessed. Litter levels were associated with port presence and showed relationship between environmental degradation, IAS and litter accumulation. Adults were more aware about both issues and their perception of litter and plant invasion were positively correlated. Results suggest enhancing marine awareness, with more effort addressed specifically to students. There is a misperception of the real magnitude of IAS and litter impacts that should be approached improving awareness about this topics in the younger generations.

<a href="../publications.html"><i class="fas fa-arrow-left"></i> Back to Publications</a>